cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,	name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),

    path('about.html/',views.aboutD,	name='aboutD'),
    path('add/<int:product_id>/about.html', views.aboutA, name='aboutA'),
    path('remove/<int:product_id>/about.html', views.aboutR,name='aboutR'),

    path('contact.html/',views.contactD,name='contactD'),
    path('add/<int:product_id>/contact.html', views.contactA, name='contactA'),
    path('remove/<int:product_id>/contact.html', views.contactR,name='contactR'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop.urls',namespace='shop')),  
    path('about.html/',include('shop.urls',namespace='shop')),
    path('contact.html/',include('shop.urls',namespace='shop')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/',	views.order_create,	name='order_create'),

    path('create/about.html',	views.about,	name='about'),

    path('create/contact.html',	views.contact,	name='contact'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('',views.product_list,	name='product_list'),
    path('<slug:category_slug>/',	views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
    
    path('about.html/',views.about,	name='about'),
    path('<slug:category_slug>/about.html/',	views.aboutProL,	name='aboutL'),
    path('<int:id>/<slug:slug>/about.html/',views.aboutProD,	name='aboutD'),
    
    path('contact.html/',views.contact,	name='contact'),
    path('<slug:category_slug>/contact.html/',views.contactProL,	name='contactL'),
    path('<int:id>/<slug:slug>/contact.html/',views.contactProD,	name='contactD'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request,	product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    
    return render(request,'cart/detail.html',{'cart':cart})

def aboutD(request):
    return render(request,'shop/about.html')

def aboutA(request,product_id):
    return render(request,'shop/about.html')

def aboutR(request,product_id):
    return render(request,'shop/about.html')

def contactD(request):
    return render(request,'shop/contact.html')

def contactA(request,product_id):
    return render(request,'shop/contact.html')

def contactR(request,product_id):
    return render(request,'shop/contact.html')

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
<div class="mainContent" style="margin-left: 242px;">
<table class="cart">
    <thead>
        <tr style="background-color: #5e98de; color: whitesmoke;">
            <th style="padding: 8px;">Image</th>
            <th style="padding: 8px;">Product</th>
            <th style="padding: 8px;">Quantity</th>
            <th style="padding: 8px;">Remove</th>
            <th style="padding: 8px;">Unit price</th>
            <th style="padding: 8px;">Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr style="background-color: #ebfaff; font-weight: bold;">
            <td style="padding: 8px;">
                <a href="{{product.get_absolute_url}}">
                    <img
                        src='{{product.imageUrl}}' width="300px" height="250px">
                </a>
            </td>
            <td style="padding: 8px;">{{ product.name }}</td>
            <td style="padding: 8px;">
                <form action="{%	url	'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Update">
                    {% csrf_token %}
                </form>
            </td>
            <td style="padding: 8px;"><a style="text-decoration: none;color: crimson;" href="{%	url	'cart:cart_remove' product.id %}">Remove</a></td>
            <td  style="padding: 8px;"class="num">${{ item.price }}</td>
            <td  style="padding: 8px;"class="num">${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total" style="background-color: #5e98de; color: whitesmoke;">
            <td style="padding: 8px;">Total</td>
            <td colspan="4"></td>
            <td style="padding: 8px;" class="num">${{ cart.get_total_price }}</td>
        </tr>
    </tbody>
</table>
</div>
<p class="text-right" style="margin-left:870px;">
    <a style="background-color: grey;text-decoration: none; color: whitesmoke;padding:5px;border-radius: 3px;" href="{%	url	'shop:product_list' %}" class="buttonlight">Continue shopping</a>
    <a style="background-color: #5e98de;text-decoration: none; color: whitesmoke;padding:5px;border-radius: 3px;" href="{%	url	'orders:order_create' %}" class="button">Checkout</a>
</p>
{% endblock %}