cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,	name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),

    path('about.html/',views.aboutD,	name='aboutD'),
    path('add/<int:product_id>/about.html', views.aboutA, name='aboutA'),
    path('remove/<int:product_id>/about.html', views.aboutR,name='aboutR'),

    path('contact.html/',views.contactD,name='contactD'),
    path('add/<int:product_id>/contact.html', views.contactA, name='contactA'),
    path('remove/<int:product_id>/contact.html', views.contactR,name='contactR'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop.urls',namespace='shop')),  
    path('about.html/',include('shop.urls',namespace='shop')),
    path('contact.html/',include('shop.urls',namespace='shop')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('',views.product_list,	name='product_list'),
    path('<slug:category_slug>/',	views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
    
    path('about.html/',views.about,	name='about'),
    path('<slug:category_slug>/about.html/',	views.aboutProL,	name='aboutL'),
    path('<int:id>/<slug:slug>/about.html/',views.aboutProD,	name='aboutD'),
    
    path('contact.html/',views.contact,	name='contact'),
    path('<slug:category_slug>/contact.html/',views.contactProL,	name='contactL'),
    path('<int:id>/<slug:slug>/contact.html/',views.contactProD,	name='contactD'),
]

shop/models.py
from email.policy import default
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name



    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)
    # image=models.ImageField(upload_to='products/%Y/%m/%d',default="")
    imageUrl=models.CharField(max_length=600)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        index_together=(('id','slug'),)

    def ___str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])

shop/views.py
from django.shortcuts import get_object_or_404, render, get_list_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product':	product,'cart_product_form':	cart_product_form})


def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        #	If	page	is	not	an	integer	deliver	the	first	page
        products= paginator.page(1)
    except EmptyPage:
        #	If	page	is	out	of	range	deliver	last	page	of	results
        products = paginator.page(paginator.num_pages)
    
    return render(request, 'shop/product/list.html', {'category': category, 'categories': categories,'products': products})


def about(request):
    return render(request, 'shop/about.html')
 
def aboutProL(request,category_slug=None):
    return render(request, 'shop/about.html')

def aboutProD(request,id, slug):
    return render(request, 'shop/about.html')


def contact(request):
    return render(request, 'shop/contact.html')

def contactProL(request,category_slug=None):
    return render(request, 'shop/contact.html')

def contactProD(request,id, slug):
    return render(request, 'shop/contact.html')

shop/templates/shop/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abouts</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap');

        body {
            padding-top: 10vh;
            background-color:rgb(248, 244, 241);
        }

        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Ubuntu', sans-serif;
            width: 80vw;
            height: 80vh;
            margin: auto;
            color: rgb(89, 86, 86);
        }

        h2 {
            font-size: 30px;

        }

        .contact-blocks {
            display: flex;
            height: 90%;
            color: rgb(75, 72, 72);
        }

        .outer-cover-cust {
            border: 1px solid bl;
        }

        .customer-care,
        .sales-marketing {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            margin: auto;
            height: 80%;
            border-radius: 25px;
        }


        .customer-care {
            width: 300px;
            border: 1px #4737d3 solid;
            margin: 25px;
            box-shadow: 0 -10px 5px #4737d3;
        }



        .sales-marketing {
            width: 300px;
            margin: 25px;
            border: 1px #55c397 solid;
            box-shadow: 0 -10px 5px #55c397;

        }

        .sales-marketing h3,
        .customer-care h3 {
            padding-top: 25px;
            text-align: center;
        }

        .sales-marketing p,
        .customer-care p {
            text-align: justify;
            margin-top: 40px;
            padding-bottom: 30px;
            text-align: center;
        }



        @media screen and (max-width:760px) {
            body {
                padding-top: 0;

            }

            .contact-blocks {
                flex-direction: column;
            }
        }

        .typeAnim {
            overflow: hidden;
            border-right: .15em light whitesmoke;
            white-space: nowrap;
            animation:
                typing 1.2s forwards;
            width: 0;
        }

        @keyframes typing {
            from {
                width: 0
            }

            to {
                width: 100%
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>About</h2>
        <div class="contact-blocks">
            <div class="customer-care">
                <h3 class="typeAnim">Hello friends, My name is Shahzad!!</h3>
                <p>I am passionate about learning and trying new technologies.</p>
            </div>

            <div class="sales-marketing">
                <p style="margin-top:120px ;">This project work is done during my internship at <b>Suven Consultants and
                        Technology Pvt. Ltd</b> under the guidance of the best industry experts.
                    It is based on the <b>Django </b>framework of python. The front-end is based on <b>HTML </b>and
                    <b>CSS.</b>
                </p>
            </div>

        </div>
    </div>
</body>

</html>

<!--
.typeAnim {
    overflow: hidden;
    border-right: .15em light whitesmoke;
    white-space: nowrap;
    animation:
        typing 1.2s forwards;
    width: 0;
}

@keyframes typing {
    from {
        width: 0
    }

    to {
        width: 100%
    }
}

@keyframes glowing {
    0% {
      background-color: #464949;
      box-shadow: 0 0 3px #6a6d69;
    }
    50% {
      background-color: #979997;
      box-shadow: 0 0 10px #9c9c9c;
    }
    100% {
      background-color: #caccc9;
      box-shadow: 0 0 3px #f0f7ee;
    }
  }
  .btn {
    animation: glowing 2500ms infinite;
  }
  -->

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %} My Shop {% endblock %}</title>
    <style>
        .navbar {
            background: #2874f0;
            margin-top: -8px;
            padding: 1px;
        }

        .navbar li {
            float: left;
            list-style: none;
            margin: 5px 7px;

        }

        .navbar li a:hover {
            background: #005e99;

        }

        .navbar ul {
            overflow: auto;
        }

        .navbar li a {
            font-family: "calibri";
            text-decoration: none;
            border-radius: 5px;
            color: white;
            padding: 5px;
            margin: 5px;
        }

        .footer {
            background-color: #2874f0;
            margin-top: 32px;
            color: white;
            text-align: center;
            font-family: Calibri;
            font-weight: bold;
            padding: 1px;
        }
        {% block style %} {% endblock %}
    </style>
</head>

<body>
    <header>
        <nav class="navbar">
            <ul>
                <li style="color: white;font-size:23px;font-family:Calibri;margin-right:26px;">My Shop</li>
                <li><a href="{% url 'shop:product_list' %}">Home</a>
                <li><a href='about.html'>About</a></li>
                <li><a href="contact.html">Contact us</a></li>
                <li>
                    <div id="subheader">
                        <div class="cart" style="margin-left:685px ;color:azure;font-weight:bold;">
                            {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                            <img src='https://www.citypng.com/public/uploads/preview/download-hd-shopping-cart-black-logo-icon-png-11640441685ymd041qjws.png' width="30px" height="20px">
                            <a href="{%	url	'cart:cart_detail' %}">
                                {{ total_items }} item{{ total_items|pluralize }},
                                ${{ cart.get_total_price }}
                            </a>
                            {% else %}
                            Your cart is empty.
                            {% endif %}
                            {% endwith %}
                
                        </div>
                    </div>
                </li>
            </ul>
            
        </nav>
    </header>
    
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="footer">
            <p>www.shopee.com</p>
            <p>All rights reserved &copy; 2022</p>
        </div>
    </footer>
</body>
</html>

shop/templates/shop/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap');
        body {
            background-color:rgb(248, 244, 241);
            padding-top: 10vh;
        }
        
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Ubuntu', sans-serif;
            width: 80vw;
            height: 80vh;
            margin: auto;
            color: rgb(89, 86, 86);
        }
        h2{
            font-size: 30px;
   
        }
        hr{
            width: 70%;
        }
        h4{
            font-size: 20px;
        }
        .contact-blocks {
            display: flex;
            height: 90%;
            color: rgb(75, 72, 72);
        }
        
        .outer-cover-cust {
            border: 1px solid bl;
        }
        
        .customer-care{
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            margin: auto;
            height: 80%;
            border-radius: 25px;
        }
        

        .customer-care {
            width: 300px;
            border: 1px #4737d3 solid;
            margin: 25px;
            box-shadow: 0 -10px 5px #4737d3;
        }
        
        .customer-care h3 {
            padding-top: 25px;
            text-align: center;
        }
        
        .customer-care p {
            padding-bottom: 40px;
            text-align: center;
           margin-top: 60px;
          font-weight: bold;
          color: #1734c3;

        }
        
        button {
            font-size: 15px;
            border-radius: 25px;
            padding: 10px 35px;
            border: 0;
            margin: 5px;
        }
        
        .customer-care button{
            background: #4737d3 ;
            color: rgb(232, 228, 228);
        }
                
        .customer-care button:hover{
            color: rgb(139, 134, 134);
        }
                
        .customer-care a {
            padding-top: 20px;
            text-decoration: none;
            font-weight:900;
            color: #4737d3;
        }
        .customer-care a:hover { 
            color: #7972b5; 
        }
        @media screen and (max-width:760px) {
            body{
                padding-top: 0;

            }
            .contact-blocks{
                flex-direction: column;
            }
        }
        .typeAnim {
            overflow: hidden;
            border-right: .15em light whitesmoke;
            white-space: nowrap;
            animation:
                typing 1.2s forwards;
            width: 0;
        }

        @keyframes typing {
            from {
                width: 0
            }

            to {
                width: 100%
            }
        }
    </style>
</head>

<body>
    <div class="container typeAnim">
        <h2>Contact Us</h2>
        <hr>
        <h4>Have any suggestions? I'd love to hear from you</h4>
        <div class="contact-blocks">
            <div class="customer-care">
                <h3>Email</h3>
                <p>shahzadsayyed1729@gmail.com</p>
            </div>

        </div>
    </div>
</body>

</html>

shop/templates/shop/pagination.html
<style>
    .step-links a{
           text-decoration: none;
           background-color: #8d8b8b;
           color: white;
           padding: 5px 13px;
       border-radius: 9px;
       margin: 5px;
    }   
    .pagination{
        margin-left: 572px;
    margin-top: 73px;
    }
    .step-links a:hover{
       background: #f66b5d;
    }
   </style>
   <div class="pagination">
       <span class="step-links">
           {% if products.has_previous %}
           <a href="?page={{	page.previous_page_number	}}">Previous</a>
           {% endif %}
           <span class="current">
               Page <b>{{ page.number }}</b> of <b>{{ page.paginator.num_pages }}</b>
           </span>
           {% if products.has_next %}
           <a href="?page={{	page.next_page_number	}}">Next</a>
           {% endif %}
       </span>
   </div>